apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: hush-redis-service
  ports:
    #ClusterIp
    - name: endpoint
      port: 6379

    #- name: http
    #  port: 6379
    #  nodePort: 30070
  

  type: NodePort